import type { Metadata } from "next"
import { DM_Sans } from "next/font/google"
import "./globals.css"
import Providers from "./providers"
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "sonner"

const dmSens = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sens",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${dmSens.className}`}>
          <Providers>
            <div className="root-layout">{children}</div>
            <Toaster richColors closeButton />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  )
}
